//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adodb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nova_ataEntities : DbContext
    {
        public nova_ataEntities()
            : base("name=nova_ataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cockpit> cockpit { get; set; }
        public virtual DbSet<cockpit_sap> cockpit_sap { get; set; }
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<logs> logs { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<tasks> tasks { get; set; }
        public virtual DbSet<team_allocation> team_allocation { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<notifications> notifications { get; set; }
    }
}
