//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class cockpit
    {
        public int cockpitId { get; set; }
        public int projectId { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public string code { get; set; }
        public string dummyCode { get; set; }
        public string parentSellCode { get; set; }
        public string parentZpac { get; set; }
        public string hash { get; set; }
    }
}
