//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class cockpit_sap
    {
        public int cockpitSAPId { get; set; }
        public string cen { get; set; }
        public string codCntrl { get; set; }
        public string material { get; set; }
        public string sellCode { get; set; }
        public string materialShortText { get; set; }
        public string createdIn { get; set; }
        public string created { get; set; }
        public string tmat { get; set; }
        public string sm { get; set; }
        public string umb { get; set; }
        public string gross { get; set; }
        public string net { get; set; }
        public string un { get; set; }
        public string volume { get; set; }
        public string uvl { get; set; }
        public string prcStand { get; set; }
        public string money { get; set; }
        public string workflow { get; set; }
        public string ident { get; set; }
        public string task { get; set; }
        public string workItemText { get; set; }
        public string status1 { get; set; }
        public string status2 { get; set; }
        public string status3 { get; set; }
        public string messageText { get; set; }
        public string responsible { get; set; }
        public string currentResponsible { get; set; }
        public string generationDate { get; set; }
        public string generationTime { get; set; }
        public string realInDate { get; set; }
        public string realExDate { get; set; }
        public string finished { get; set; }
        public string endTime { get; set; }
        public string deadline { get; set; }
        public string utlEndTime { get; set; }
    }
}
