//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int commentId { get; set; }
        public int taskId { get; set; }
        public string comment { get; set; }
        public int owner { get; set; }
        public string creationDate { get; set; }
        public string creationTime { get; set; }
    
        public virtual users users { get; set; }
        public virtual tasks tasks { get; set; }
    }
}
