//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs
    {
        public int logId { get; set; }
        public string controller { get; set; }
        public string requestType { get; set; }
        public int requester { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string attribute1 { get; set; }
        public string attribute2 { get; set; }
        public string body { get; set; }
    
        public virtual users users { get; set; }
    }
}
