//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class notifications
    {
        public int projectId { get; set; }
        public string status { get; set; }
    
        public virtual projects projects { get; set; }
    }
}
