//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tasks()
        {
            this.comments = new HashSet<comments>();
        }
    
        public int taskId { get; set; }
        public int projectId { get; set; }
        public string notifyMe { get; set; }
        public string meetingDate { get; set; }
        public string product { get; set; }
        public string pWork { get; set; }
        public string criticalActivity { get; set; }
        public string activityTitle { get; set; }
        public string activityDescription { get; set; }
        public string parent { get; set; }
        public string grandParent { get; set; }
        public string responsible { get; set; }
        public string start { get; set; }
        public string finish { get; set; }
        public string status { get; set; }
        public string activityOrigin { get; set; }
        public string idProjectTask { get; set; }
        public string idParentProjectTask { get; set; }
        public string ident { get; set; }
        public string hash { get; set; }
        public string delayReason { get; set; }
        public string delayDescription { get; set; }
        public Nullable<int> createdBy { get; set; }
        public string creationDate { get; set; }
        public Nullable<int> reworkCount { get; set; }
        public string actualFinishDate { get; set; }
        public string newStart { get; set; }
        public string newFinish { get; set; }
        public string isFreezed { get; set; }
        public string wasDeleted { get; set; }
        public string wasInsertedAfterFreezing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
        public virtual projects projects { get; set; }
        public virtual users users { get; set; }
    }
}
