//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adodb
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_allocation
    {
        public int teamAllocationId { get; set; }
        public int projectId { get; set; }
        public int userId { get; set; }
        public string status { get; set; }
        public string gate { get; set; }
        public string allocationStartDate { get; set; }
        public string allocationFinishDate { get; set; }
    
        public virtual projects projects { get; set; }
        public virtual users users { get; set; }
    }
}
